
    create table routines (
        created_date timestamp(6),
        id bigint generated by default as identity,
        name varchar(255),
        user_id varchar(255),
        primary key (id)
    );

    create table task_completion (
        date date not null,
        is_complete boolean not null,
        completed_time timestamp(6),
        id bigint generated by default as identity,
        task_id bigint,
        primary key (id)
    );

    create table tasks (
        created_date timestamp(6),
        id bigint generated by default as identity,
        routine_id bigint,
        name varchar(255),
        primary key (id)
    );

    create table users (
        created_date timestamp(6),
        id bigint generated by default as identity,
        email varchar(255),
        firebase_id varchar(255),
        username varchar(255),
        primary key (id)
    );

    alter table if exists task_completion 
       add constraint FKag1qbp6gmisxysm7b69j7h0fq 
       foreign key (task_id) 
       references tasks;

    alter table if exists tasks 
       add constraint FKfnkf62r08t5bahahfe7yskqs8 
       foreign key (routine_id) 
       references routines;
